
trigger:
- main
- dev

variables:
  - name: azureSubscription
    value: '84c5f8d6-c21b-49e6-8b88-bca28abb3d85'
  - name: vmImageName
    value: 'ubuntu-latest'
  - name: workingDirectory
    value: '.'
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    - group: settings-prod
    - name: functionAppName
      value: 'ai-bestrong'
    - name: env
      value: production

  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/dev') }}:
    - group: settings
    - name: functionAppName
      value: 'ai-bestrong'
    - name: env
      value: development


stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.6'
      inputs:
        versionSpec: 3.10 

    - bash: |
        pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
      workingDirectory: $(workingDirectory)
      displayName: 'Install application dependencies'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(workingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'production'
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:

          steps:
          - task: AzureFunctionApp@1
            displayName: 'Azure functions app deploy'
            inputs:
              azureSubscription: 'Azure for Students (85bd95c0-eabe-403c-87b6-f72ae70ec867)'
              appType: 'functionAppLinux'
              appName: '$(functionAppName)'
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              runtimeStack: 'PYTHON|3.10'
              appSettings: '-STORAGE_ACCOUNT_CONNECTION_STRIN $(STORAGE_ACCOUNT_CONNECTION_STRING) -DOCUMENTAI_ENDPOINT $(DOCUMENTAI_ENDPOINT) -DOCUMENTAI_KEY $(DOCUMENTAI_KEY) -WEBSITE_RUN_FROM_PACKAGE 1 -CONTAINER $(CONTAINER) -FILE_SHARE $(FILE_SHARE)'